# Site
title: Thiago Hersan
description: Thiago Hersan
author: Thiago Hersan

# URL
url: https://thiagohersan.com
baseurl: ''
permalink: project/:title/
include: ['_pages']

# Build settings
markdown: kramdown
port: 4444

# Data
social:
  facebook_url: "https://www.facebook.com/thiago.hersan"
  twitter_url: "https://www.twitter.com/thiagohersan"
  twitter_user: "@thiagohersan"
  vimeo_url: "https://vimeo.com/thiagohersan"
  github_url: "https://github.com/thiagohersan"
